services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://Library:Library123@cluster0.g0m2zn8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
