name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Docker on the runner
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or your container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Images for Frontend and Backend
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/library-backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/library-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/library-frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/library-frontend:latest

      # SSH into Deployment Server and Deploy
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
