name: Mirror to Classroom Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to Classroom Repo
        env:
          CLASSROOM_PAT: ${{ secrets.CLASSROOM_PAT }}
        run: |
          git remote set-url classroom https://Mizzaka:${{ secrets.CLASSROOM_PAT }}@github.com/Plymouth-University/coursework-group_66.git
          git push classroom main --force
