name: Mirror to Classroom Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up git configuration
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Add classroom remote and push to classroom repo
        env:
          CLASSROOM_PAT: ${{ secrets.CLASSROOM_PAT }}
        run: |
          git remote add classroom https://Mizzaka:${CLASSROOM_PAT}@github.com/Plymouth-University/coursework-group_66.git
          git push classroom main --force
